image: gitpod/workspace-full

tasks:
  - init: yarn install && yarn run build
    command: cd ./examples && yarn start

vscode:
  extensions:
    - esbenp.prettier-vscode@6.3.2:13e527ae62035854197198eedd2bc84f