image: gitpod/workspace-full

tasks:
  - name: install node_modules
    init: yarn install && cd examples/ && yarn install
  - name: link react-xarrows to examples
    init: yarn link && cd examples/ && yarn link react-xarrows
  - name: ts watch
    command: tsc -w
  - name: start examples
    command: cd examples/ && yarn start

vscode:
  extensions:
    - esbenp.prettier-vscode@6.3.2:13e527ae62035854197198eedd2bc84f